name: lol_random_builds
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:

dependencies:
  cupertino_icons: ^1.0.2
  dio: ^5.4.1
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.10
  flutter_typeahead: ^5.2.0
  go_router: ^13.2.0
  toggle_switch: ^2.2.1

dev_dependencies:
  change_app_package_name: ^1.1.0
  flutter_lints: ^3.0.2
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/data/
    - assets/images/champions/
    - assets/images/items/
    - assets/images/runes/
    - assets/images/stats/
    - assets/images/summoners/
