name: lol_random_builds
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.0.0

dependencies:
  cupertino_icons: ^1.0.2
  dio: ^5.4.1
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.3.11
  flutter_riverpod: ^2.4.10
  flutter_typeahead: ^5.2.0
  go_router: ^14.0.2
  google_mobile_ads: ^4.0.0
  toggle_switch: ^2.2.1

dev_dependencies:
  change_app_package_name: ^1.1.0
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.2
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.jpg"
  min_sdk_android: 21

flutter_native_splash:
  image: "assets/images/icon.jpg"
  color: "#252829"

  android_12:
    image: "assets/images/icon.jpg"
    color: "#252829"

  android: true
  ios: true
  
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/data/
    - assets/images/champions/
    - assets/images/items/
    - assets/images/runes/
    - assets/images/stats/
    - assets/images/summoners/
